// Auto-generated from Cascade Excel data - Do not edit manually

export interface CascadeTask {
  id: string;
  name: string;
  level: "Hedef" | "Proje" | "Alt Görev";
  source: "Türkiye" | "Kurumsal" | "International";
  planName: string;
  progress: number;
  status: "On Track" | "Achieved" | "Behind" | "At Risk" | "Not Started";
  startDate: string;
  endDate: string;
  leader: string;
}

export interface CascadeHedef {
  id: string;
  name: string;
  source: string;
  status: string;
  leader: string;
  startDate: string;
  endDate: string;
  projects: CascadeProje[];
}

export interface CascadeProje {
  id: string;
  name: string;
  status: string;
  leader: string;
  startDate: string;
  endDate: string;
  tasks: CascadeGorev[];
}

export interface CascadeGorev {
  id: string;
  name: string;
  progress: number;
  status: string;
  startDate: string;
  endDate: string;
}

export const turkiyeHedefler: CascadeHedef[] = [
{
  id: "turkiye-1",
  name: "Antep Fıstığı Ürünlerinin Çin Pazarına Girişi",
  source: "Türkiye",
  status: "On Track",
  leader: "Ozan Yeşilyer",
  startDate: "2022-11-01",
  endDate: "2025-01-01",
  projects: [
  {
    id: "prj-2",
    name: "Antep fıstığının Çin pazarına girmesi",
    status: "Behind",
    leader: "Ozan Yeşilyer",
    startDate: "2022-11-01",
    endDate: "2025-01-01",
    tasks: [
    {
      id: "tsk-3",
      name: "1-Pazar analizi",
      progress: 100,
      status: "Achieved",
      startDate: "2022-11-01",
      endDate: "2023-05-30",
    },
    {
      id: "tsk-4",
      name: "2-Rakip analizi",
      progress: 100,
      status: "Achieved",
      startDate: "2023-01-01",
      endDate: "2023-01-01",
    },
    {
      id: "tsk-5",
      name: "3-Teşvik sistemlerinin incelenmesi",
      progress: 100,
      status: "Achieved",
      startDate: "2024-01-01",
      endDate: "2024-03-31",
    },
    {
      id: "tsk-6",
      name: "4-Bölge şube kuruluşu",
      progress: 100,
      status: "Achieved",
      startDate: "2024-02-01",
      endDate: "2024-08-31",
    },
    {
      id: "tsk-7",
      name: "5-Satış kanallarının oluşturulması",
      progress: 100,
      status: "Achieved",
      startDate: "2023-01-01",
      endDate: "2025-01-01",
    },
    {
      id: "tsk-8",
      name: "6-Stratejik stok bulundurma",
      progress: 50,
      status: "At Risk",
      startDate: "2024-08-01",
      endDate: "2025-01-01",
    }
    ],
  }
  ],
},
{
  id: "turkiye-9",
  name: "Muş Bölgesi Sulama Altyapısı Modernizasyonu",
  source: "Türkiye",
  status: "On Track",
  leader: "Recep Mergen",
  startDate: "2020-12-07",
  endDate: "2025-05-25",
  projects: [
  {
    id: "prj-10",
    name: "Muş Bölgesi Sulama Altyapısı Modernizasyonu devreye alınması ve verimli kullanma",
    status: "On Track",
    leader: "Recep Mergen",
    startDate: "2020-12-07",
    endDate: "2025-05-25",
    tasks: [
    {
      id: "tsk-11",
      name: "7-B2-B3-B7 Proje İnşaat İşleri",
      progress: 100,
      status: "Achieved",
      startDate: "2021-04-01",
      endDate: "2021-06-30",
    },
    {
      id: "tsk-12",
      name: "3-B2-B3-B7 Proje Su İhtiyaç Analizi",
      progress: 100,
      status: "Achieved",
      startDate: "2020-06-01",
      endDate: "2020-06-30",
    },
    {
      id: "tsk-13",
      name: "2-B2-B3-B7 Proje Fizibilite Çalışması",
      progress: 100,
      status: "Achieved",
      startDate: "2020-06-01",
      endDate: "2020-06-30",
    },
    {
      id: "tsk-14",
      name: "3-B2-B3-B7 Proje Çizimleri ve Mühendislik Çalışmaları",
      progress: 100,
      status: "Achieved",
      startDate: "2020-06-01",
      endDate: "2020-06-30",
    },
    {
      id: "tsk-15",
      name: "4-B2-B3-B7 Taşeron Seçimi ve Anlaşması",
      progress: 100,
      status: "Achieved",
      startDate: "2020-08-01",
      endDate: "2020-08-01",
    },
    {
      id: "tsk-16",
      name: "6-B2-B3-B7 Proje Kazı Çalışmaları",
      progress: 100,
      status: "Achieved",
      startDate: "2020-09-01",
      endDate: "2021-04-30",
    },
    {
      id: "tsk-17",
      name: "6-B2-B3-B7 Tarla İçi Dağıtım Hattı Yeraltı Sulama Borusu Kurulumu",
      progress: 100,
      status: "Achieved",
      startDate: "2020-09-01",
      endDate: "2021-05-31",
    },
    {
      id: "tsk-18",
      name: "9-B1-B5 Sulama İhtiyaç Analizi",
      progress: 100,
      status: "Achieved",
      startDate: "2021-04-01",
      endDate: "2021-04-30",
    },
    {
      id: "tsk-19",
      name: "11-B1-B5 Proje Fizibilite Çalışması",
      progress: 100,
      status: "Achieved",
      startDate: "2021-04-01",
      endDate: "2021-08-31",
    },
    {
      id: "tsk-20",
      name: "10-B2-B3-B7 Dağıtım Hattı Test Edilmesi",
      progress: 100,
      status: "Achieved",
      startDate: "2021-05-01",
      endDate: "2021-08-31",
    },
    {
      id: "tsk-21",
      name: "11-B1-B5 Proje Fizibilite Çalışması",
      progress: 100,
      status: "Achieved",
      startDate: "2021-05-01",
      endDate: "2021-08-31",
    },
    {
      id: "tsk-22",
      name: "12-B1-B5 Proje Çizimleri ve Mühendislik Çalışmaları",
      progress: 100,
      status: "Achieved",
      startDate: "2021-05-01",
      endDate: "2021-08-31",
    },
    {
      id: "tsk-23",
      name: "13-B1-B5 Taşeron Seçimi ve Anlaşması",
      progress: 100,
      status: "Achieved",
      startDate: "2021-09-01",
      endDate: "2021-10-01",
    },
    {
      id: "tsk-24",
      name: "14-B1-B5 Proje Kazı Çalışmaları",
      progress: 100,
      status: "Achieved",
      startDate: "2021-09-01",
      endDate: "2021-12-31",
    },
    {
      id: "tsk-25",
      name: "15-B1-B5 Tarla İçi Dağıtım Hattı Yeraltı Sulama Kurulumu ve Montaj",
      progress: 100,
      status: "Achieved",
      startDate: "2021-11-01",
      endDate: "2021-12-31",
    },
    {
      id: "tsk-26",
      name: "17-B1-B5 Ana Filtrasyon Kurulumu",
      progress: 100,
      status: "Achieved",
      startDate: "2022-05-01",
      endDate: "2022-05-31",
    },
    {
      id: "tsk-27",
      name: "18-B1-B5 Murat Nehri İsale Hattı Boru Kurulumu ve Montajı",
      progress: 100,
      status: "Achieved",
      startDate: "2022-05-01",
      endDate: "2022-05-31",
    },
    {
      id: "tsk-28",
      name: "18-B2-B3-B7 Sisteme Su Verilmesi ve Sulama Yapılması",
      progress: 100,
      status: "Achieved",
      startDate: "2022-05-01",
      endDate: "2022-06-30",
    },
    {
      id: "tsk-29",
      name: "19-B2-B3-B7 Sisteme Su Verilmesi ve Sulama Yapılması",
      progress: 50,
      status: "At Risk",
      startDate: "2023-12-01",
      endDate: "2026-01-01",
    },
    {
      id: "tsk-30",
      name: "20-B1-B5 Murat Nehri İsale Hattı Test Edilmesi",
      progress: 100,
      status: "Achieved",
      startDate: "2023-12-01",
      endDate: "2026-01-01",
    },
    {
      id: "tsk-31",
      name: "21-B1-B5 Murat Nehri Su Sağlama Noktası Otomasyonu",
      progress: 100,
      status: "Achieved",
      startDate: "2024-05-01",
      endDate: "2024-06-30",
    },
    {
      id: "tsk-32",
      name: "22-B1-B5 Dağıtım Hattı Testi",
      progress: 100,
      status: "Achieved",
      startDate: "2024-08-01",
      endDate: "2026-01-01",
    },
    {
      id: "tsk-33",
      name: "23-B1-B5 Sisteme Su Verilmesi ve Sulama Yapılması",
      progress: 100,
      status: "Achieved",
      startDate: "2024-08-01",
      endDate: "2025-11-01",
    }
    ],
  }
  ],
},
{
  id: "turkiye-34",
  name: "Muş Arazisi Tarımsal Mekanizasyon Kapasitesinin Güçlendirilmesi",
  source: "Türkiye",
  status: "On Track",
  leader: "Recep Mergen",
  startDate: "2025-05-01",
  endDate: "2026-07-01",
  projects: [
  {
    id: "prj-35",
    name: "Yıldız Muş Arazisi Tarımsal Mekanizasyon Projesi",
    status: "On Track",
    leader: "Recep Mergen",
    startDate: "2025-01-01",
    endDate: "2026-07-01",
    tasks: [
    {
      id: "tsk-36",
      name: "1 adet 9 m iş genişliğinde Hububat mibzeri",
      progress: 100,
      status: "Achieved",
      startDate: "2025-01-01",
      endDate: "2026-07-01",
    },
    {
      id: "tsk-37",
      name: "2 adet 9 m Azaltılmış toprak İşleme Ekipmanı",
      progress: 100,
      status: "Achieved",
      startDate: "2025-01-01",
      endDate: "2026-07-01",
    },
    {
      id: "tsk-38",
      name: "2 adet 9 m iş genişliğinde sıraya ekim mibzeri",
      progress: 100,
      status: "Achieved",
      startDate: "2025-01-01",
      endDate: "2026-07-01",
    },
    {
      id: "tsk-39",
      name: "2 adet 450 HP traktör",
      progress: 100,
      status: "Achieved",
      startDate: "2025-01-01",
      endDate: "2026-07-01",
    }
    ],
  }
  ],
},
{
  id: "turkiye-40",
  name: "Rejeneratif Tarım Uygulamalarının Yaygınlaştırılması",
  source: "Türkiye",
  status: "On Track",
  leader: "Recep Mergen",
  startDate: "2025-01-01",
  endDate: "2026-12-31",
  projects: [
  {
    id: "prj-41",
    name: "Faz 1 - Değişkenli Tarım (2024-2025 Sezonu)",
    status: "On Track",
    leader: "Recep Mergen",
    startDate: "2023-10-21",
    endDate: "2026-12-01",
    tasks: [
    {
      id: "tsk-42",
      name: "1- Örtü Bitkilerinin Ekilmesi",
      progress: 100,
      status: "Achieved",
      startDate: "2023-10-21",
      endDate: "2026-12-01",
    },
    {
      id: "tsk-43",
      name: "2- Düşük Dozlarda Gübre Uygulamaları",
      progress: 100,
      status: "Achieved",
      startDate: "2023-10-21",
      endDate: "2026-12-01",
    },
    {
      id: "tsk-44",
      name: "3- Rejeneratif Tarıma Uygun Ekipman Alımı",
      progress: 100,
      status: "Achieved",
      startDate: "2023-10-21",
      endDate: "2026-10-31",
    },
    {
      id: "tsk-45",
      name: "4- Yeni Alınan Ekipmanlara Uygun Toprak İşlemelerinin Yapılması",
      progress: 100,
      status: "Achieved",
      startDate: "2023-10-21",
      endDate: "2026-10-31",
    }
    ],
  },
  {
    id: "prj-46",
    name: "Faz 2 - Rejeneratif Tarım (2025-2026 Sezonu)",
    status: "At Risk",
    leader: "Recep Mergen",
    startDate: "2024-10-01",
    endDate: "2026-12-31",
    tasks: [
    {
      id: "tsk-47",
      name: "1- Örtü bitkisi ve etkileri",
      progress: 100,
      status: "Achieved",
      startDate: "2024-04-04",
      endDate: "2025-10-31",
    },
    {
      id: "tsk-48",
      name: "2- Striptill uygulaması ve sonuçları",
      progress: 50,
      status: "At Risk",
      startDate: "2024-10-01",
      endDate: "2026-12-31",
    },
    {
      id: "tsk-49",
      name: "3- Subsoiler uygulaması ve sonuçları",
      progress: 50,
      status: "At Risk",
      startDate: "2024-10-01",
      endDate: "2026-12-31",
    }
    ],
  }
  ],
},
{
  id: "turkiye-50",
  name: "Yem Katkı Ürünleri İhracat Satışlarının Artırılması",
  source: "Türkiye",
  status: "On Track",
  leader: "Taylan Eğilmez",
  startDate: "2024-07-01",
  endDate: "2026-06-30",
  projects: [
  {
    id: "prj-51",
    name: "Yem katkı ihracat arttırılması, Yem katkı ve premix ve yiy-dışı pazar genişlet.",
    status: "Behind",
    leader: "Taylan Eğilmez",
    startDate: "2024-07-01",
    endDate: "2026-06-30",
    tasks: [
    {
      id: "tsk-52",
      name: "1-Kıbrıs pazarında amino asit satışlarının arttırılması",
      progress: 100,
      status: "Achieved",
      startDate: "2024-07-01",
      endDate: "2026-06-30",
    },
    {
      id: "tsk-53",
      name: "2-Azerbaycan pazarında premix ve amino asit satışlarını arttırarak devamı",
      progress: 100,
      status: "Achieved",
      startDate: "2024-07-01",
      endDate: "2026-06-30",
    },
    {
      id: "tsk-54",
      name: "3-USA aminoasit için Eppen veya Dongxiao görüşmeler, Sunrise işbirliği",
      progress: 100,
      status: "Achieved",
      startDate: "2024-07-01",
      endDate: "2026-06-30",
    },
    {
      id: "tsk-55",
      name: "4-Suriye'ye Çin'den aminoasit, Triden aminoasit ve premix satışlarının başlaması",
      progress: 50,
      status: "At Risk",
      startDate: "2024-07-01",
      endDate: "2026-06-30",
    },
    {
      id: "tsk-56",
      name: "5-Suriye'ye 1 Kişinin alınması",
      progress: 50,
      status: "At Risk",
      startDate: "2025-09-01",
      endDate: "2026-06-30",
    },
    {
      id: "tsk-57",
      name: "6-Suriye'ye satışların artırılması",
      progress: 50,
      status: "At Risk",
      startDate: "2025-09-01",
      endDate: "2026-06-30",
    },
    {
      id: "tsk-58",
      name: "7-Irak'a Türkiye ve Çin'den aminoasit satışlarının başlaması",
      progress: 100,
      status: "Achieved",
      startDate: "2024-07-01",
      endDate: "2026-06-30",
    },
    {
      id: "tsk-59",
      name: "8-Irak'a 1 kişinin alınması",
      progress: 100,
      status: "Achieved",
      startDate: "2025-09-01",
      endDate: "2026-06-30",
    }
    ],
  }
  ],
},
{
  id: "turkiye-60",
  name: "Yıldız Alparslan Anıtkır Yatırımında Arsa Edinimi",
  source: "Türkiye",
  status: "On Track",
  leader: "Recep Mergen",
  startDate: "2025-03-01",
  endDate: "2027-12-01",
  projects: [
  {
    id: "prj-61",
    name: "Yıldız Alparslan Anıtkır Yatırımında Arsa Edinimi",
    status: "On Track",
    leader: "Recep Mergen",
    startDate: "2025-03-01",
    endDate: "2027-12-01",
    tasks: [
    {
      id: "tsk-62",
      name: "1-Mevcut Alanımızı Arttırmak",
      progress: 100,
      status: "Achieved",
      startDate: "2025-03-01",
      endDate: "2027-12-01",
    },
    {
      id: "tsk-63",
      name: "2-Verimli ve sulanabilir arazilerin satınalınması / uzun dönem kiralanması",
      progress: 50,
      status: "On Track",
      startDate: "2025-03-01",
      endDate: "2027-12-31",
    }
    ],
  }
  ],
}
];

export const kurumsalHedefler: CascadeHedef[] = [
{
  id: "kurumsal-64",
  name: "Deniz-Nehir Tipi Gemi İnşa Yatırımının Gerçekleştirilmesi",
  source: "Kurumsal",
  status: "On Track",
  leader: "İdris İlhan Telci",
  startDate: "2024-01-01",
  endDate: "2026-03-31",
  projects: [
  {
    id: "prj-65",
    name: "2 adet 8330 dwt'lik Deniz-Nehir tipi gemi inşa projesi",
    status: "On Track",
    leader: "İdris İlhan Telci",
    startDate: "2024-01-01",
    endDate: "2026-03-31",
    tasks: [
    {
      id: "tsk-66",
      name: "1-Fizibilite",
      progress: 0,
      status: "Achieved",
      startDate: "2024-01-01",
      endDate: "2024-05-28",
    },
    {
      id: "tsk-67",
      name: "2-İnşa yapacak tersanenin ve gemi tipinin belirlenmesi",
      progress: 0,
      status: "Achieved",
      startDate: "2024-01-01",
      endDate: "2024-05-28",
    },
    {
      id: "tsk-68",
      name: "3-Tersane ve Leasing anlaşmalarının yapılması",
      progress: 0,
      status: "Achieved",
      startDate: "2024-01-01",
      endDate: "2024-05-28",
    },
    {
      id: "tsk-69",
      name: "4-Gemi inşası",
      progress: 0,
      status: "On Track",
      startDate: "2024-11-01",
      endDate: "2026-03-31",
    }
    ],
  }
  ],
},
{
  id: "kurumsal-70",
  name: "Bireysel Performans Yönetim Sisteminin Kurulması",
  source: "Kurumsal",
  status: "On Track",
  leader: "Güven Emrah Erenler",
  startDate: "2024-08-05",
  endDate: "2025-11-30",
  projects: [
  {
    id: "prj-71",
    name: "Bireysel Performans Yönetim Sistemi'nin kurulması",
    status: "On Track",
    leader: "Güven Emrah Erenler",
    startDate: "2024-08-05",
    endDate: "2025-11-30",
    tasks: [
    {
      id: "tsk-72",
      name: "1-Proje ekibinin kurulması, kapsam ve hedefin net tanımlanması",
      progress: 0,
      status: "Achieved",
      startDate: "2024-08-05",
      endDate: "2024-08-14",
    },
    {
      id: "tsk-73",
      name: "2-Piyasa en iyi uygulamalarının araştırması ve analizi",
      progress: 0,
      status: "Achieved",
      startDate: "2024-08-15",
      endDate: "2024-09-16",
    },
    {
      id: "tsk-74",
      name: "3-Tiryaki performans sistemi önerilerinin geliştirilmesi",
      progress: 0,
      status: "Achieved",
      startDate: "2024-09-16",
      endDate: "2024-10-31",
    },
    {
      id: "tsk-75",
      name: "4-Üst yönetim sunum ve onay aşaması",
      progress: 0,
      status: "On Track",
      startDate: "2025-05-01",
      endDate: "2025-05-30",
    },
    {
      id: "tsk-76",
      name: "5-Prosedürlerin hazırlanması, iletişim, performans formlarının oluşturulması",
      progress: 0,
      status: "On Track",
      startDate: "2025-06-02",
      endDate: "2025-11-30",
    }
    ],
  }
  ],
},
{
  id: "kurumsal-77",
  name: "Buğday Derin İşleme Tesisi Yatırımının Hayata Geçirilmesi",
  source: "Kurumsal",
  status: "On Track",
  leader: "Suat Söbüçovalı",
  startDate: "2024-06-01",
  endDate: "2027-07-31",
  projects: [
  {
    id: "prj-78",
    name: "Buğday Derin İşleme Tesisi Yatırımının Hayata Geçirilmesi",
    status: "On Track",
    leader: "Suat Söbüçovalı",
    startDate: "2024-06-01",
    endDate: "2027-07-31",
    tasks: [
    {
      id: "tsk-79",
      name: "1-Land Allocation",
      progress: 0,
      status: "Achieved",
      startDate: "2024-12-10",
      endDate: "2025-06-15",
    },
    {
      id: "tsk-80",
      name: "2-Business Plan",
      progress: 0,
      status: "Achieved",
      startDate: "2024-06-10",
      endDate: "2025-06-15",
    },
    {
      id: "tsk-81",
      name: "3-Design Engineering",
      progress: 0,
      status: "Achieved",
      startDate: "2024-11-01",
      endDate: "2025-05-10",
    },
    {
      id: "tsk-82",
      name: "4-Selection of Technology and Management Suppliers",
      progress: 0,
      status: "At Risk",
      startDate: "2024-06-01",
      endDate: "2026-12-31",
    },
    {
      id: "tsk-83",
      name: "5-Commissioning",
      progress: 0,
      status: "Not Started",
      startDate: "2027-03-01",
      endDate: "2027-07-31",
    }
    ],
  }
  ],
},
{
  id: "kurumsal-84",
  name: "Çiftlik Yönetim Sistemi FarmERP Entegrasyonu",
  source: "Kurumsal",
  status: "At Risk",
  leader: "Kerime İkizler",
  startDate: "2026-02-02",
  endDate: "2026-12-31",
  projects: [
  {
    id: "prj-85",
    name: "Çiftlik Yönetim Sistemi FarmERP Entegrasyonu",
    status: "At Risk",
    leader: "Kerime İkizler",
    startDate: "2026-02-02",
    endDate: "2026-12-31",
    tasks: [
    {
      id: "tsk-86",
      name: "Milestone 0: Discovery & Onsite Understanding",
      progress: 0,
      status: "On Track",
      startDate: "2026-02-02",
      endDate: "2026-12-31",
    },
    {
      id: "tsk-87",
      name: "Milestone 1: Kick-Off Meeting",
      progress: 0,
      status: "On Track",
      startDate: "2026-03-01",
      endDate: "2026-03-02",
    },
    {
      id: "tsk-88",
      name: "Milestone 2: Business Process Walk Through",
      progress: 0,
      status: "Not Started",
      startDate: "2026-03-15",
      endDate: "2026-03-31",
    },
    {
      id: "tsk-89",
      name: "Milestone 3: System Configuration",
      progress: 0,
      status: "Not Started",
      startDate: "2026-03-22",
      endDate: "2026-04-05",
    },
    {
      id: "tsk-90",
      name: "Milestone 4: Master Data Migration",
      progress: 0,
      status: "Not Started",
      startDate: "2026-04-12",
      endDate: "2026-04-26",
    },
    {
      id: "tsk-91",
      name: "Milestone 5: End User Training",
      progress: 0,
      status: "Not Started",
      startDate: "2026-04-27",
      endDate: "2026-05-10",
    },
    {
      id: "tsk-92",
      name: "Milestone 6: UAT/Trail Runs",
      progress: 0,
      status: "Not Started",
      startDate: "2026-05-10",
      endDate: "2026-05-24",
    },
    {
      id: "tsk-93",
      name: "Milestone 7: Go-Live Data Migration",
      progress: 0,
      status: "Not Started",
      startDate: "2026-05-24",
      endDate: "2026-06-07",
    },
    {
      id: "tsk-94",
      name: "Milestone 8: Go-Live",
      progress: 0,
      status: "Not Started",
      startDate: "2026-06-01",
      endDate: "2026-06-07",
    }
    ],
  }
  ],
},
{
  id: "kurumsal-95",
  name: "Giresun Protein Tesisi Kapasite Artırımı",
  source: "Kurumsal",
  status: "On Track",
  leader: "Murat Solak",
  startDate: "2024-05-01",
  endDate: "2026-05-31",
  projects: [
  {
    id: "prj-96",
    name: "Giresun protein tesisi 2. kısım kapasite arttırım projesi",
    status: "On Track",
    leader: "Murat Solak",
    startDate: "2024-05-01",
    endDate: "2026-05-31",
    tasks: [
    {
      id: "tsk-97",
      name: "1-Giresun Ayçekirdeği tesis kapasitesinin arttırılması için araştırmalar yapılması",
      progress: 0,
      status: "Achieved",
      startDate: "2024-05-01",
      endDate: "2024-06-13",
    },
    {
      id: "tsk-98",
      name: "2-Proje için gerekli ekipmanların belirlenmesi",
      progress: 0,
      status: "Achieved",
      startDate: "2024-06-16",
      endDate: "2024-08-11",
    },
    {
      id: "tsk-99",
      name: "3-İlgili çözüm yolları ile ilgili tedarikçi görüşmelerinin başlanması",
      progress: 0,
      status: "Achieved",
      startDate: "2024-08-13",
      endDate: "2024-09-22",
    },
    {
      id: "tsk-100",
      name: "4-İlgili verilerin üst yönetime sunulması ve proje bütçesinin onaylanması",
      progress: 0,
      status: "Achieved",
      startDate: "2024-09-29",
      endDate: "2024-10-27",
    },
    {
      id: "tsk-101",
      name: "5-Tedarikçi ile anlaşmanın imzalanması",
      progress: 0,
      status: "Achieved",
      startDate: "2024-10-21",
      endDate: "2024-10-31",
    },
    {
      id: "tsk-102",
      name: "6-Ekipmanların satın alma sürecinin tamamlanması",
      progress: 0,
      status: "On Track",
      startDate: "2025-02-10",
      endDate: "2025-10-31",
    },
    {
      id: "tsk-103",
      name: "7-Tesisin kurulumu ve devreye alınması",
      progress: 0,
      status: "Not Started",
      startDate: "2025-11-01",
      endDate: "2026-05-31",
    }
    ],
  }
  ],
},
{
  id: "kurumsal-104",
  name: "Grup Sigorta Strateji ve Prosedürleri",
  source: "Kurumsal",
  status: "On Track",
  leader: "Nazlı Deniz Çetin",
  startDate: "2025-01-01",
  endDate: "2027-09-30",
  projects: [
  {
    id: "prj-105",
    name: "Tiryaki Sigorta Strateji & Prosedürlerinin Belirlenmesi ve Yürürlüğe Konması",
    status: "On Track",
    leader: "Nazlı Deniz Çetin",
    startDate: "2025-01-01",
    endDate: "2027-09-30",
    tasks: [
    {
      id: "tsk-106",
      name: "1-Grup Şirketlerini Kapsar Genel Sigorta Stratejisinin Belirlenmesi",
      progress: 0,
      status: "On Track",
      startDate: "2025-01-01",
      endDate: "2026-06-01",
    },
    {
      id: "tsk-107",
      name: "2-Belirlenen Strateji'ye Göre Poliçe/Teminat Bazlı Prosedürlerin Oluşturulması",
      progress: 0,
      status: "Not Started",
      startDate: "2026-03-01",
      endDate: "2026-12-31",
    },
    {
      id: "tsk-108",
      name: "3-Yazılan Prosedürler için Üst Yönetim Onayının Alınması",
      progress: 0,
      status: "Not Started",
      startDate: "2026-03-01",
      endDate: "2026-09-30",
    },
    {
      id: "tsk-109",
      name: "4-Prosedürlerin Grup Bünyesindeki Şirketlere Tebliğ Edilip Uygulanması",
      progress: 0,
      status: "Not Started",
      startDate: "2026-12-31",
      endDate: "2027-06-01",
    },
    {
      id: "tsk-110",
      name: "5-Süreçler, Satın Alma ve Hasarlar ile İlgili Eğitimlerin Verilmesi",
      progress: 0,
      status: "Not Started",
      startDate: "2027-03-30",
      endDate: "2027-09-30",
    }
    ],
  }
  ],
},
{
  id: "kurumsal-111",
  name: "Grup Şirketleri Sigorta Yönetimi ERP Modülü Entegrasyonu",
  source: "Kurumsal",
  status: "On Track",
  leader: "Nazlı Deniz Çetin",
  startDate: "2024-08-01",
  endDate: "2027-07-31",
  projects: [
  {
    id: "prj-112",
    name: "Grup Şirketleri Genelinde Sigorta Süreçlerinin ERP Sistemine Uyarlanması",
    status: "On Track",
    leader: "Nazlı Deniz Çetin",
    startDate: "2024-08-01",
    endDate: "2027-07-31",
    tasks: [
    {
      id: "tsk-113",
      name: "1-Üretim ve Hasar Datalarının ERP Sistemine Yüklenmesi",
      progress: 0,
      status: "On Track",
      startDate: "2024-08-01",
      endDate: "2025-12-31",
    },
    {
      id: "tsk-114",
      name: "2-ERP Raporlama Düzeninin Belirlenmesi ve Data Girişlerinin Yapılması",
      progress: 0,
      status: "Not Started",
      startDate: "2025-07-31",
      endDate: "2026-07-31",
    },
    {
      id: "tsk-115",
      name: "3-Hasar Süreçlerinde İş Birimi Bilgi ve Belgelerinin ERP Kayıt & Akış Entegrasyonu",
      progress: 0,
      status: "Not Started",
      startDate: "2025-07-31",
      endDate: "2026-07-31",
    },
    {
      id: "tsk-116",
      name: "4-Satın Alma Süreçlerinde İş Birimi Belgelerinin ERP Kayıt & Akış Entegrasyonu",
      progress: 0,
      status: "Not Started",
      startDate: "2025-07-31",
      endDate: "2026-07-31",
    },
    {
      id: "tsk-117",
      name: "5-Oluşturulan ERP Sisteminin Tüm Grup Şirketlerine Entegrasyonu",
      progress: 0,
      status: "Not Started",
      startDate: "2026-07-31",
      endDate: "2027-07-31",
    },
    {
      id: "tsk-118",
      name: "6-Sigorta Yönetimi ERP Modülünün Global Grup Şirketlerine Tanıtım Eğitimi",
      progress: 0,
      status: "Not Started",
      startDate: "2026-07-31",
      endDate: "2027-07-31",
    }
    ],
  }
  ],
},
{
  id: "kurumsal-119",
  name: "Sigortalanabilir Değer Tespit & Güncelleme",
  source: "Kurumsal",
  status: "On Track",
  leader: "Nazlı Deniz Çetin",
  startDate: "2024-08-15",
  endDate: "2026-06-01",
  projects: [
  {
    id: "prj-120",
    name: "MKT Süreçlerinin Uygun Bir Şekilde Yönetimi",
    status: "On Track",
    leader: "Nazlı Deniz Çetin",
    startDate: "2024-08-15",
    endDate: "2026-06-01",
    tasks: [
    {
      id: "tsk-121",
      name: "1-Tesislerin Sigortalanabilir Değerlerinin Tespiti için Saha Ziyaret Planlaması",
      progress: 0,
      status: "Achieved",
      startDate: "2024-08-25",
      endDate: "2024-09-13",
    },
    {
      id: "tsk-122",
      name: "2-Tesis Sigortalanabilir Kıymetlerin Değer Kontrol ve Tespiti",
      progress: 0,
      status: "On Track",
      startDate: "2024-09-13",
      endDate: "2024-10-16",
    },
    {
      id: "tsk-123",
      name: "3-Yatırım Departmanı ile Tesiste Tespit Edilen Bedellerin Kontrol ve Teyidi",
      progress: 0,
      status: "Achieved",
      startDate: "2024-10-15",
      endDate: "2024-11-16",
    },
    {
      id: "tsk-124",
      name: "4-Sigortalanabilir Kıymetlerin Grup Şirketler Bazında Ayrıştırılması",
      progress: 0,
      status: "Achieved",
      startDate: "2024-09-01",
      endDate: "2024-11-01",
    },
    {
      id: "tsk-125",
      name: "5-Sigortalanabilir Kıymetlerin Düzenli Değerleme & Kontrol Sistemi Oluşturulması",
      progress: 0,
      status: "At Risk",
      startDate: "2025-01-01",
      endDate: "2026-06-01",
    }
    ],
  }
  ],
},
{
  id: "kurumsal-126",
  name: "HR & ADC Entegrasyonu",
  source: "Kurumsal",
  status: "On Track",
  leader: "Kerime İkizler",
  startDate: "2024-08-18",
  endDate: "2025-08-31",
  projects: [
  {
    id: "prj-127",
    name: "HR&ADC Entegrasyon Projesi",
    status: "On Track",
    leader: "Kerime İkizler",
    startDate: "2024-08-18",
    endDate: "2025-08-31",
    tasks: [
    {
      id: "tsk-128",
      name: "1-Planlama",
      progress: 0,
      status: "Achieved",
      startDate: "2024-08-18",
      endDate: "2024-08-20",
    },
    {
      id: "tsk-129",
      name: "2-Hazırlık ve Test Aşaması",
      progress: 0,
      status: "Achieved",
      startDate: "2024-08-18",
      endDate: "2024-09-24",
    },
    {
      id: "tsk-130",
      name: "3-Yeni AD & Tenant Entegrasyonu",
      progress: 0,
      status: "Achieved",
      startDate: "2024-08-18",
      endDate: "2024-08-20",
    },
    {
      id: "tsk-131",
      name: "4-ERP HR & Active Directory Entegrasyonu",
      progress: 0,
      status: "Achieved",
      startDate: "2024-09-23",
      endDate: "2024-09-30",
    },
    {
      id: "tsk-132",
      name: "5-ERP HR ve Active Directory Entegrasyonunun Test İşlemleri",
      progress: 0,
      status: "Achieved",
      startDate: "2024-08-26",
      endDate: "2024-10-22",
    },
    {
      id: "tsk-133",
      name: "6-Contact Sync Entra ID Kullanıcıları İçin Üyelik Senkronizasyonu",
      progress: 0,
      status: "Achieved",
      startDate: "2024-08-26",
      endDate: "2024-09-18",
    },
    {
      id: "tsk-134",
      name: "7-ERP HR ve Active Directory Entegrasyonunun Devreye Alınması",
      progress: 0,
      status: "On Track",
      startDate: "2024-10-14",
      endDate: "2026-02-27",
    }
    ],
  }
  ],
},
{
  id: "kurumsal-135",
  name: "Integrity Project",
  source: "Kurumsal",
  status: "On Track",
  leader: "Suat Söbüçovalı",
  startDate: "2024-02-04",
  endDate: "2027-12-12",
  projects: [
  {
    id: "prj-136",
    name: "Integrity Project",
    status: "On Track",
    leader: "Suat Söbüçovalı",
    startDate: "2024-02-04",
    endDate: "2027-12-12",
    tasks: [
    {
      id: "tsk-137",
      name: "1-Project Incentive & Corporations",
      progress: 0,
      status: "On Track",
      startDate: "2024-03-01",
      endDate: "2026-03-01",
    },
    {
      id: "tsk-138",
      name: "2-Theoretical and Compositional Analysis",
      progress: 0,
      status: "Achieved",
      startDate: "2024-02-04",
      endDate: "2024-05-31",
    },
    {
      id: "tsk-139",
      name: "3-Scope and Concept",
      progress: 0,
      status: "Achieved",
      startDate: "2025-04-04",
      endDate: "2025-12-31",
    },
    {
      id: "tsk-140",
      name: "4-Pilot Scale Testings",
      progress: 0,
      status: "On Track",
      startDate: "2024-09-01",
      endDate: "2026-09-01",
    },
    {
      id: "tsk-141",
      name: "5-Business Plan & FM",
      progress: 0,
      status: "On Track",
      startDate: "2025-08-01",
      endDate: "2025-12-31",
    },
    {
      id: "tsk-142",
      name: "6-Selection of Technology and Suppliers",
      progress: 0,
      status: "Not Started",
      startDate: "2025-08-04",
      endDate: "2026-06-01",
    },
    {
      id: "tsk-143",
      name: "7-Commissioning",
      progress: 0,
      status: "Not Started",
      startDate: "2026-03-31",
      endDate: "2027-12-12",
    }
    ],
  }
  ],
},
{
  id: "kurumsal-144",
  name: "Kurumsal İntranet Portalının Devreye Alınması",
  source: "Kurumsal",
  status: "On Track",
  leader: "Arzu Örsel",
  startDate: "2025-05-11",
  endDate: "2025-12-30",
  projects: [
  {
    id: "prj-145",
    name: "Kurumsal İntranet Portalının Devreye Alınması - Tedarikçi belirlenmesi ve satınalma süreci",
    status: "On Track",
    leader: "Arzu Örsel",
    startDate: "2025-05-11",
    endDate: "2025-12-30",
    tasks: [
    {
      id: "tsk-146",
      name: "1-Bütçe onayı, tedarikçi belirlenmesi, satınalma sürecinin tamamlanması",
      progress: 0,
      status: "On Track",
      startDate: "2025-05-11",
      endDate: "2025-07-09",
    },
    {
      id: "tsk-147",
      name: "2-Tasarımın tamamlanması, içerik başlıklarının belirlenmesi",
      progress: 0,
      status: "On Track",
      startDate: "2025-06-25",
      endDate: "2025-10-24",
    },
    {
      id: "tsk-148",
      name: "3-Türkçe ve İngilizce içeriklerin oluşturulması ve girişlerinin tamamlanması",
      progress: 0,
      status: "On Track",
      startDate: "2025-08-22",
      endDate: "2025-12-31",
    },
    {
      id: "tsk-149",
      name: "4-İnsan Kaynakları sistemleri ile entegrasyonun tamamlanması",
      progress: 0,
      status: "Not Started",
      startDate: "2025-09-18",
      endDate: "2026-05-15",
    },
    {
      id: "tsk-150",
      name: "5-Mavi yakalar ile ilişkin geliştirmelerin tamamlanması",
      progress: 0,
      status: "Not Started",
      startDate: "2025-09-28",
      endDate: "2026-05-16",
    }
    ],
  }
  ],
},
{
  id: "kurumsal-151",
  name: "ITSM Projesi",
  source: "Kurumsal",
  status: "On Track",
  leader: "Kerime İkizler",
  startDate: "2025-06-02",
  endDate: "2026-03-31",
  projects: [
  {
    id: "prj-152",
    name: "ITSM Projesi",
    status: "On Track",
    leader: "Kerime İkizler",
    startDate: "2025-06-02",
    endDate: "2026-03-31",
    tasks: [
    {
      id: "tsk-153",
      name: "1-Analiz ve Sistem Tasarımı",
      progress: 0,
      status: "Achieved",
      startDate: "2025-03-15",
      endDate: "2025-07-31",
    },
    {
      id: "tsk-154",
      name: "2-Xurrent Kurulumunun Tamamlanması",
      progress: 0,
      status: "Achieved",
      startDate: "2025-06-15",
      endDate: "2025-06-30",
    },
    {
      id: "tsk-155",
      name: "3-Sistem Destek",
      progress: 0,
      status: "Achieved",
      startDate: "2025-07-01",
      endDate: "2025-07-08",
    },
    {
      id: "tsk-156",
      name: "4-Canlıya Taşıma",
      progress: 0,
      status: "Achieved",
      startDate: "2025-08-18",
      endDate: "2025-08-31",
    },
    {
      id: "tsk-157",
      name: "5-Canlı Sonrası Destek",
      progress: 0,
      status: "Achieved",
      startDate: "2025-09-01",
      endDate: "2025-09-30",
    },
    {
      id: "tsk-158",
      name: "6-Raporlama Çalışmaları",
      progress: 0,
      status: "Achieved",
      startDate: "2025-10-15",
      endDate: "2025-11-30",
    },
    {
      id: "tsk-159",
      name: "7-Hizmet Seviyesi Yönetimi",
      progress: 0,
      status: "Achieved",
      startDate: "2025-10-03",
      endDate: "2025-10-31",
    },
    {
      id: "tsk-160",
      name: "8-Proje Yönetimi",
      progress: 0,
      status: "Achieved",
      startDate: "2025-10-05",
      endDate: "2025-11-30",
    },
    {
      id: "tsk-161",
      name: "9-Değişiklik Yönetimi",
      progress: 0,
      status: "On Track",
      startDate: "2026-01-01",
      endDate: "2026-02-28",
    },
    {
      id: "tsk-162",
      name: "10-BT Varlık Yönetimi",
      progress: 0,
      status: "On Track",
      startDate: "2026-03-02",
      endDate: "2026-04-01",
    },
    {
      id: "tsk-163",
      name: "11-DevOps Entegrasyon",
      progress: 0,
      status: "On Track",
      startDate: "2025-11-24",
      endDate: "2026-01-26",
    },
    {
      id: "tsk-164",
      name: "12-Problem Yönetimi",
      progress: 0,
      status: "Not Started",
      startDate: "2026-02-27",
      endDate: "2026-03-31",
    },
    {
      id: "tsk-165",
      name: "13-Yazılım Geliştirme (Scrum Workspace)",
      progress: 0,
      status: "Not Started",
      startDate: "2026-02-22",
      endDate: "2026-03-31",
    }
    ],
  }
  ],
},
{
  id: "kurumsal-166",
  name: "Kazakistan Buğday İşleme Tesisi Kurulumu",
  source: "Kurumsal",
  status: "On Track",
  leader: "Yiğit Karacı",
  startDate: "2024-04-01",
  endDate: "2027-06-30",
  projects: [
  {
    id: "prj-167",
    name: "Kazakistan Buğday Tesisi kurulumu",
    status: "On Track",
    leader: "Yiğit Karacı",
    startDate: "2024-04-01",
    endDate: "2027-06-30",
    tasks: [
    {
      id: "tsk-168",
      name: "1-Business Plan dökümanlarının hazırlanması",
      progress: 0,
      status: "Achieved",
      startDate: "2024-04-01",
      endDate: "2025-01-16",
    },
    {
      id: "tsk-169",
      name: "2-Şirketin kurulması",
      progress: 0,
      status: "Achieved",
      startDate: "2024-04-01",
      endDate: "2024-06-30",
    },
    {
      id: "tsk-170",
      name: "3-Layout projesinin çizilmesi",
      progress: 0,
      status: "Achieved",
      startDate: "2024-07-28",
      endDate: "2024-08-04",
    },
    {
      id: "tsk-171",
      name: "4-Teknoloji firmasının seçilmesi",
      progress: 0,
      status: "On Track",
      startDate: "2024-09-02",
      endDate: "2025-08-31",
    },
    {
      id: "tsk-172",
      name: "5-İnşaat işlerinin tamamlanması",
      progress: 0,
      status: "Not Started",
      startDate: "2025-09-01",
      endDate: "2027-05-31",
    },
    {
      id: "tsk-173",
      name: "6-Test ve Devreye Alma",
      progress: 0,
      status: "Not Started",
      startDate: "2027-06-01",
      endDate: "2027-06-30",
    }
    ],
  }
  ],
},
{
  id: "kurumsal-174",
  name: "Mamul Depo Konveyör Hattı Uzatım Projesi",
  source: "Kurumsal",
  status: "On Track",
  leader: "Emre Padar",
  startDate: "2024-08-09",
  endDate: "2025-10-31",
  projects: [
  {
    id: "prj-175",
    name: "Mamul Depo Konveyör Hattı Uzatım Projesi projesi",
    status: "On Track",
    leader: "Emre Padar",
    startDate: "2024-08-09",
    endDate: "2025-10-31",
    tasks: [
    {
      id: "tsk-176",
      name: "1-Piyasa araştırılması yapılması",
      progress: 0,
      status: "Achieved",
      startDate: "2024-08-09",
      endDate: "2024-09-01",
    },
    {
      id: "tsk-177",
      name: "2-Aksiyon planı oluşturulması",
      progress: 0,
      status: "Achieved",
      startDate: "2024-09-02",
      endDate: "2024-09-15",
    },
    {
      id: "tsk-178",
      name: "3-Uygun çözümlerin araştırılması ve en uygun seçeneğin belirlenmesi",
      progress: 0,
      status: "Achieved",
      startDate: "2024-09-15",
      endDate: "2024-11-12",
    },
    {
      id: "tsk-179",
      name: "4-Bütçe planlaması ve kaynaklar tahsisi",
      progress: 0,
      status: "On Track",
      startDate: "2024-11-15",
      endDate: "2025-05-31",
    },
    {
      id: "tsk-180",
      name: "5-Operasyon süreçlerinde uygulamaya başlanması",
      progress: 0,
      status: "Not Started",
      startDate: "2025-06-01",
      endDate: "2025-10-31",
    }
    ],
  }
  ],
},
{
  id: "kurumsal-181",
  name: "NOLA İskele Altyapı Yatırımı",
  source: "Kurumsal",
  status: "On Track",
  leader: "Yiğit Karacı",
  startDate: "2025-01-01",
  endDate: "2027-06-01",
  projects: [
  {
    id: "prj-182",
    name: "Faz1 - NOLA İskele ve Depo Yenileme, Raylı Sistem Entegrasyonu",
    status: "On Track",
    leader: "Yiğit Karacı",
    startDate: "2025-01-01",
    endDate: "2026-06-15",
    tasks: [
    {
      id: "tsk-183",
      name: "1-Son yerleşim düzenine göre makine, ekipman, maliyet çalışması yapılması",
      progress: 0,
      status: "Achieved",
      startDate: "2024-07-29",
      endDate: "2024-08-12",
    },
    {
      id: "tsk-184",
      name: "2-Amerika'nın yerlisi bir Proje Müdürü'nün bulunması",
      progress: 0,
      status: "Achieved",
      startDate: "2024-07-31",
      endDate: "2025-01-01",
    },
    {
      id: "tsk-185",
      name: "3-Contractor seçiminin yapılması",
      progress: 0,
      status: "Achieved",
      startDate: "2024-11-18",
      endDate: "2025-02-02",
    },
    {
      id: "tsk-186",
      name: "4-Yenilenme sürecinin tamamlanması",
      progress: 0,
      status: "On Track",
      startDate: "2025-07-10",
      endDate: "2025-09-30",
    },
    {
      id: "tsk-187",
      name: "5-Satınalma işlerinin yapılması",
      progress: 0,
      status: "On Track",
      startDate: "2025-02-13",
      endDate: "2025-07-31",
    },
    {
      id: "tsk-188",
      name: "6-Test ve devreye alma sürecinin tamamlanması",
      progress: 0,
      status: "Not Started",
      startDate: "2025-09-01",
      endDate: "2025-09-30",
    }
    ],
  },
  {
    id: "prj-189",
    name: "Faz2 - Deodorizasyon Ünitesinin Rafineriye Dön. & Yenilenebilir Yağ Tankları",
    status: "Not Started",
    leader: "Yiğit Karacı",
    startDate: "2027-06-01",
    endDate: "2027-06-01",
    tasks: [
    {
      id: "tsk-190",
      name: "1-Layout projesinin çizilmesi",
      progress: 0,
      status: "On Track",
      startDate: "2025-07-01",
      endDate: "2025-07-07",
    },
    {
      id: "tsk-191",
      name: "2-Temel mühendislik tasarımlarının hazırlanması",
      progress: 0,
      status: "On Track",
      startDate: "2025-08-07",
      endDate: "2025-11-30",
    },
    {
      id: "tsk-192",
      name: "3-EPC Yüklenicisinin seçilmesi",
      progress: 0,
      status: "Not Started",
      startDate: "2025-12-01",
      endDate: "2025-12-31",
    },
    {
      id: "tsk-193",
      name: "4-Proje İnşaat süreci",
      progress: 0,
      status: "Not Started",
      startDate: "2026-07-01",
      endDate: "2027-05-31",
    },
    {
      id: "tsk-194",
      name: "5-Test ve Devreye Alma",
      progress: 0,
      status: "Not Started",
      startDate: "2026-05-31",
      endDate: "2026-06-30",
    }
    ],
  }
  ],
},
{
  id: "kurumsal-195",
  name: "Operasyonel KPK Belirleme ve Faaliyet Raporu",
  source: "Kurumsal",
  status: "On Track",
  leader: "Burcu Gözen",
  startDate: "2025-01-01",
  endDate: "2026-01-01",
  projects: [
  {
    id: "prj-196",
    name: "Operasyonel KPK belirleme ve BI rapor çalışması",
    status: "On Track",
    leader: "Burcu Gözen",
    startDate: "2025-01-01",
    endDate: "2026-01-01",
    tasks: [
    {
      id: "tsk-197",
      name: "1-Üretim KPI, holding genelinde rapor ve ölçümlenen KPI'ların incelenmesi",
      progress: 0,
      status: "Achieved",
      startDate: "2025-01-01",
      endDate: "2025-07-01",
    },
    {
      id: "tsk-198",
      name: "2-Takip edilecek operasyonel KPI listesinin belirlenmesi",
      progress: 0,
      status: "Achieved",
      startDate: "2025-01-01",
      endDate: "2025-06-30",
    },
    {
      id: "tsk-199",
      name: "3-Proje ekibinin belirlenmesi, dep. yöneticileri ve finans ekibiyle görüşülmesi",
      progress: 0,
      status: "Behind",
      startDate: "2025-07-01",
      endDate: "2026-03-31",
    },
    {
      id: "tsk-200",
      name: "4-İhtiyaç duyulan data kaynaklarının belirlenmesi",
      progress: 0,
      status: "Achieved",
      startDate: "2025-06-01",
      endDate: "2025-10-31",
    },
    {
      id: "tsk-201",
      name: "5-KPI'ların Power BI platformuna taşınması",
      progress: 0,
      status: "Behind",
      startDate: "2025-09-01",
      endDate: "2026-03-31",
    },
    {
      id: "tsk-202",
      name: "6-BI raporlarının yönetim ve operasyon ekibinin kullanımına sunulması",
      progress: 0,
      status: "Not Started",
      startDate: "2025-07-01",
      endDate: "2026-04-30",
    }
    ],
  }
  ],
},
{
  id: "kurumsal-203",
  name: "Organik Ürün İzlenebilirlik Sisteminin Dijitalleştirilmesi",
  source: "Kurumsal",
  status: "At Risk",
  leader: "Kübra Dömbek",
  startDate: "2024-07-01",
  endDate: "2026-03-31",
  projects: [
  {
    id: "prj-204",
    name: "Organik İzlenebilirlik Dijitalleştirme",
    status: "At Risk",
    leader: "Kübra Dömbek",
    startDate: "2024-07-01",
    endDate: "2026-03-31",
    tasks: [
    {
      id: "tsk-205",
      name: "1-RFQ hazırlanması",
      progress: 0,
      status: "Achieved",
      startDate: "2024-07-01",
      endDate: "2024-07-10",
    },
    {
      id: "tsk-206",
      name: "2-Kalite Departmanı Doküman Yönetim Sistemi / İş Akış Süreç Belirleme",
      progress: 0,
      status: "Achieved",
      startDate: "2024-07-24",
      endDate: "2024-07-31",
    },
    {
      id: "tsk-207",
      name: "3-ERP Tetikleme Noktaları Belirlenmesi",
      progress: 0,
      status: "At Risk",
      startDate: "2024-11-15",
      endDate: "2025-07-01",
    },
    {
      id: "tsk-208",
      name: "4-Formların Dijitalleştirilmesi",
      progress: 0,
      status: "At Risk",
      startDate: "2024-12-01",
      endDate: "2025-07-01",
    },
    {
      id: "tsk-209",
      name: "5-Kontrollerin yapılması",
      progress: 0,
      status: "Achieved",
      startDate: "2025-05-30",
      endDate: "2025-07-31",
    },
    {
      id: "tsk-210",
      name: "6-El terminallerinin satın alım sürecinin tamamlanması",
      progress: 0,
      status: "Behind",
      startDate: "2025-08-31",
      endDate: "2026-03-31",
    },
    {
      id: "tsk-211",
      name: "7-Depo Temizlik Formu/Hammadde Alım Formu'nun tetiklenmesi ve entegrasyonu",
      progress: 0,
      status: "Not Started",
      startDate: "2025-08-31",
      endDate: "2025-12-31",
    },
    {
      id: "tsk-212",
      name: "8-Faz 1: Depo Temizlik Formu ve Hammadde Alım Formu'nun demo ortamında çalışması",
      progress: 0,
      status: "Not Started",
      startDate: "2025-08-31",
      endDate: "2026-02-28",
    },
    {
      id: "tsk-213",
      name: "9-Faz 2 olarak kalan diğer formların entegrasyonunun yapılması ve dijitalizasyonu",
      progress: 0,
      status: "Not Started",
      startDate: "2025-12-31",
      endDate: "2026-03-31",
    }
    ],
  }
  ],
},
{
  id: "kurumsal-214",
  name: "Pillar-2 Modeli",
  source: "Kurumsal",
  status: "On Track",
  leader: "Devrim Aşkın",
  startDate: "2024-08-01",
  endDate: "2026-12-31",
  projects: [
  {
    id: "prj-215",
    name: "Pillar-2 Modeli (Yerel ve Küresel Asgari Kurumlar Vergisi müessesi)",
    status: "On Track",
    leader: "Devrim Aşkın",
    startDate: "2024-08-01",
    endDate: "2026-12-31",
    tasks: [
    {
      id: "tsk-216",
      name: "1-Tiryaki Holding açısından Pillar-2 Modeline ilişkin etki analizi",
      progress: 0,
      status: "Achieved",
      startDate: "2024-08-01",
      endDate: "2024-11-15",
    },
    {
      id: "tsk-217",
      name: "2-Etki analizi sonucunda tespit edilen bulgular üzerinden bir yol haritası",
      progress: 0,
      status: "Achieved",
      startDate: "2024-11-15",
      endDate: "2024-11-30",
    },
    {
      id: "tsk-218",
      name: "3-Grup genelinde reorganizasyon modellerinin çalışılması",
      progress: 0,
      status: "Achieved",
      startDate: "2024-12-01",
      endDate: "2025-05-16",
    },
    {
      id: "tsk-219",
      name: "4-Uygulanmasına karar verilen modellerin uygulamaya geçirilmesi",
      progress: 0,
      status: "Behind",
      startDate: "2025-05-15",
      endDate: "2026-08-31",
    },
    {
      id: "tsk-220",
      name: "5-Gerekli verilerin toplanması ve gerekli beyanların yapılması",
      progress: 0,
      status: "At Risk",
      startDate: "2026-01-01",
      endDate: "2026-12-31",
    }
    ],
  }
  ],
},
{
  id: "kurumsal-221",
  name: "Sigorta Risk Değerlendirme Çalışması",
  source: "Kurumsal",
  status: "On Track",
  leader: "Nazlı Deniz Çetin",
  startDate: "2025-01-01",
  endDate: "2027-07-01",
  projects: [
  {
    id: "prj-222",
    name: "Riziko Teftiş Çalışması",
    status: "On Track",
    leader: "Nazlı Deniz Çetin",
    startDate: "2025-01-01",
    endDate: "2027-07-01",
    tasks: [
    {
      id: "tsk-223",
      name: "1-Yurt İçi Tesislerde Risk Müh. ve Tesis Yetkilileri ile Saha Ziyaretleri Planlanması",
      progress: 0,
      status: "On Track",
      startDate: "2025-09-30",
      endDate: "2026-05-31",
    },
    {
      id: "tsk-224",
      name: "2-Tavsiyeler ve Alınması Gereken Aksiyonların Tesislerle Koordinasyonu",
      progress: 0,
      status: "On Track",
      startDate: "2025-05-31",
      endDate: "2026-06-30",
    },
    {
      id: "tsk-225",
      name: "3-Düzenli Takiplerin Yapılması ve Tesislerde Risk Açığını Sıfırlamak",
      progress: 0,
      status: "Not Started",
      startDate: "2026-03-31",
      endDate: "2027-07-01",
    }
    ],
  }
  ],
},
{
  id: "kurumsal-226",
  name: "SharePoint Altyapı Göçü ve Modernizasyonu",
  source: "Kurumsal",
  status: "On Track",
  leader: "Kerime İkizler",
  startDate: "2024-06-24",
  endDate: "2025-12-31",
  projects: [
  {
    id: "prj-227",
    name: "SharePoint Altyapı Göçü ve Modernizasyonu",
    status: "On Track",
    leader: "Kerime İkizler",
    startDate: "2024-06-24",
    endDate: "2025-12-31",
    tasks: [
    {
      id: "tsk-228",
      name: "1-Kavramsal Tasarım ve Ön Gerekliliklerinin Gerçekleştirilmesi",
      progress: 0,
      status: "Achieved",
      startDate: "2024-07-01",
      endDate: "2024-07-16",
    },
    {
      id: "tsk-229",
      name: "2-Mevcut Durum Analiz ve Geçiş Planlaması",
      progress: 0,
      status: "Achieved",
      startDate: "2024-06-24",
      endDate: "2024-08-02",
    },
    {
      id: "tsk-230",
      name: "3-Pilot Geçiş & Geçiş Planının Finalize Edilmesi",
      progress: 0,
      status: "Achieved",
      startDate: "2024-08-10",
      endDate: "2024-10-19",
    },
    {
      id: "tsk-231",
      name: "4-Yaygınlaştırma",
      progress: 0,
      status: "On Track",
      startDate: "2024-11-01",
      endDate: "2026-02-27",
    },
    {
      id: "tsk-232",
      name: "5-Eğitim ve Proje Kapanış",
      progress: 0,
      status: "Not Started",
      startDate: "2025-05-01",
      endDate: "2025-12-31",
    }
    ],
  }
  ],
},
{
  id: "kurumsal-233",
  name: "Sıfır İş Kazası Hedefine Ulaşılması",
  source: "Kurumsal",
  status: "On Track",
  leader: "Ahmet Kalkan / Halil İbrahim Öztürk",
  startDate: "2024-01-01",
  endDate: "2026-12-31",
  projects: [
  {
    id: "prj-234",
    name: "Sıfır İş Kazası Hedefine Ulaşılması Projesi",
    status: "On Track",
    leader: "Ahmet Kalkan / Halil İbrahim Öztürk",
    startDate: "2024-01-01",
    endDate: "2026-12-31",
    tasks: [
    {
      id: "tsk-235",
      name: "1-İSG'nin idari işlerden ayrılarak ayrı bir departman olarak yapılandırılması",
      progress: 0,
      status: "Achieved",
      startDate: "2024-09-02",
      endDate: "2024-09-20",
    },
    {
      id: "tsk-236",
      name: "2-İSG departman yöneticisinin iş görüşmeleri ve işe alım sürecinin tamamlanması",
      progress: 0,
      status: "Achieved",
      startDate: "2024-09-20",
      endDate: "2025-01-01",
    },
    {
      id: "tsk-237",
      name: "3-İSG Yöneticisinin oryantasyonunun tamamlanması",
      progress: 0,
      status: "Achieved",
      startDate: "2025-02-28",
      endDate: "2025-03-31",
    },
    {
      id: "tsk-238",
      name: "4-Global İSG Organizasyon planının çıkartılması",
      progress: 0,
      status: "Achieved",
      startDate: "2025-05-01",
      endDate: "2025-06-01",
    },
    {
      id: "tsk-239",
      name: "5-Global İSG Organizasyon Planının Onaylanması",
      progress: 0,
      status: "Achieved",
      startDate: "2025-08-01",
      endDate: "2025-09-30",
    },
    {
      id: "tsk-240",
      name: "6-En temel 6 İSG sürecinin global yapı için prosedürleştirilmesi",
      progress: 0,
      status: "Achieved",
      startDate: "2025-06-30",
      endDate: "2025-12-01",
    },
    {
      id: "tsk-241",
      name: "7-6 Temel İSG Sürecinin İcra'dan başlayarak yönetim ekibiyle paylaşılması",
      progress: 0,
      status: "At Risk",
      startDate: "2025-11-02",
      endDate: "2026-06-25",
    },
    {
      id: "tsk-242",
      name: "8-6 Temel İSG sürecinin tesisler ile eğitimlerle paylaşılması",
      progress: 0,
      status: "Achieved",
      startDate: "2025-11-02",
      endDate: "2025-12-31",
    },
    {
      id: "tsk-243",
      name: "9-Bütçe doğrultusunda 3 temel risk değerlendirmesinin başlatılması",
      progress: 0,
      status: "Not Started",
      startDate: "2025-10-26",
      endDate: "2026-05-29",
    }
    ],
  }
  ],
},
{
  id: "kurumsal-244",
  name: "Sunrise Apollo Projesi",
  source: "Kurumsal",
  status: "At Risk",
  leader: "Kerime İkizler",
  startDate: "2025-09-15",
  endDate: "2026-05-01",
  projects: [
  {
    id: "prj-245",
    name: "Sunrise Apollo Projesi",
    status: "At Risk",
    leader: "Kerime İkizler",
    startDate: "2025-09-15",
    endDate: "2026-05-01",
    tasks: [
    {
      id: "tsk-246",
      name: "2-To Be",
      progress: 0,
      status: "On Track",
      startDate: "2026-01-19",
      endDate: "2026-03-02",
    },
    {
      id: "tsk-247",
      name: "3-IT Gap Analysis",
      progress: 0,
      status: "Not Started",
      startDate: "2026-03-16",
      endDate: "2026-05-01",
    }
    ],
  }
  ],
},
{
  id: "kurumsal-248",
  name: "Kurumsal Sürdürülebilirlik Raporlamasının Standartlaştırılması",
  source: "Kurumsal",
  status: "On Track",
  leader: "Arzu Örsel",
  startDate: "2024-07-02",
  endDate: "2026-03-06",
  projects: [
  {
    id: "prj-249",
    name: "Kurumsal Sürdürülebilirlik Raporlamasının Standartlaştırılması",
    status: "On Track",
    leader: "Arzu Örsel",
    startDate: "2024-07-02",
    endDate: "2026-03-06",
    tasks: [
    {
      id: "tsk-250",
      name: "1-Tiryaki Agro ve Anadolu Holding rapor içerikleriyle ilgili verilerin toplanması",
      progress: 0,
      status: "Achieved",
      startDate: "2024-08-18",
      endDate: "2025-07-31",
    },
    {
      id: "tsk-251",
      name: "2-Tiryaki Agro ve Anadolu Holding rapor planı & gereklilikleri için İcra onayı",
      progress: 0,
      status: "Achieved",
      startDate: "2024-09-20",
      endDate: "2025-03-25",
    },
    {
      id: "tsk-252",
      name: "3-Tiryaki Anadolu Holding raporunun yazılması ve revizyonu",
      progress: 0,
      status: "Achieved",
      startDate: "2024-08-18",
      endDate: "2025-05-30",
    },
    {
      id: "tsk-253",
      name: "4-Tiryaki Agro raporunun yazılması ve revizyonların tamamlanması",
      progress: 0,
      status: "Achieved",
      startDate: "2025-06-17",
      endDate: "2026-01-15",
    },
    {
      id: "tsk-254",
      name: "5-Tiryaki Agro Rapor tasarım ve son onay aşaması",
      progress: 0,
      status: "Achieved",
      startDate: "2025-09-15",
      endDate: "2026-01-15",
    },
    {
      id: "tsk-255",
      name: "6-Tiryaki Agro Raporun web sitelerinde yayımlanması",
      progress: 0,
      status: "Achieved",
      startDate: "2025-09-30",
      endDate: "2026-01-15",
    },
    {
      id: "tsk-256",
      name: "7-GRI Onayı",
      progress: 0,
      status: "On Track",
      startDate: "2025-11-10",
      endDate: "2026-04-15",
    }
    ],
  }
  ],
},
{
  id: "kurumsal-257",
  name: "Takdir ve Ödüllendirme Sisteminin Kurulması",
  source: "Kurumsal",
  status: "On Track",
  leader: "Tarkan Ferhat Yılmaz",
  startDate: "2024-06-11",
  endDate: "2026-06-30",
  projects: [
  {
    id: "prj-258",
    name: "Takdir ve ödüllendirme sisteminin kurulması",
    status: "On Track",
    leader: "Tarkan Ferhat Yılmaz",
    startDate: "2024-06-11",
    endDate: "2026-06-30",
    tasks: [
    {
      id: "tsk-259",
      name: "1-Proje ekibi ve planlamasının yapılması, kapsam ve hedefin net tanımlaması",
      progress: 0,
      status: "Achieved",
      startDate: "2024-06-11",
      endDate: "2024-06-28",
    },
    {
      id: "tsk-260",
      name: "2-Piyasa en iyi uygulamaları araştırma ve analiz (uygulanabilirlik/fayda)",
      progress: 0,
      status: "On Track",
      startDate: "2024-07-08",
      endDate: "2025-05-31",
    },
    {
      id: "tsk-261",
      name: "3-Tiryaki uygulama önerileri ve bütçe etkilerinin çalışılması",
      progress: 0,
      status: "On Track",
      startDate: "2024-10-10",
      endDate: "2026-05-30",
    },
    {
      id: "tsk-262",
      name: "4-Yönetim sunumu ve onay aşaması",
      progress: 0,
      status: "Not Started",
      startDate: "2025-06-01",
      endDate: "2026-06-30",
    },
    {
      id: "tsk-263",
      name: "5-Uygulamalar için zaman/iletişim planlamaları, prosedürlerin tamamlanması",
      progress: 0,
      status: "Not Started",
      startDate: "2025-11-30",
      endDate: "2026-06-30",
    }
    ],
  }
  ],
},
{
  id: "kurumsal-264",
  name: "Tiryaki Agro Global İnovasyon Merkezi (TAGIC)",
  source: "Kurumsal",
  status: "On Track",
  leader: "Suat Söbüçovalı",
  startDate: "2024-10-01",
  endDate: "2028-12-31",
  projects: [
  {
    id: "prj-265",
    name: "Tiryaki Agro Global İnovasyon Merkezi (TAGIC)",
    status: "On Track",
    leader: "Suat Söbüçovalı",
    startDate: "2024-10-01",
    endDate: "2028-12-31",
    tasks: [
    {
      id: "tsk-266",
      name: "1-Konsept, İcra Kurulu Onayı ve İç İletişim",
      progress: 0,
      status: "Achieved",
      startDate: "2024-10-01",
      endDate: "2024-12-31",
    },
    {
      id: "tsk-267",
      name: "2-Fiziki Alt Yapının Belirlenmesi",
      progress: 0,
      status: "On Track",
      startDate: "2025-01-01",
      endDate: "2026-01-01",
    },
    {
      id: "tsk-268",
      name: "3-Program, Proje ve İşbirliği Başvuruları",
      progress: 0,
      status: "On Track",
      startDate: "2025-01-01",
      endDate: "2026-01-01",
    },
    {
      id: "tsk-269",
      name: "4-Fiziki Alt Yapının Tamamlanması",
      progress: 0,
      status: "Not Started",
      startDate: "2026-01-01",
      endDate: "2026-10-01",
    },
    {
      id: "tsk-270",
      name: "5-Ar-Ge Merkezi Başvurusu ve Bakanlık Onayı",
      progress: 0,
      status: "Not Started",
      startDate: "2027-01-01",
      endDate: "2027-03-01",
    },
    {
      id: "tsk-271",
      name: "6-Destek Lokasyonlarının Kurulması",
      progress: 0,
      status: "Not Started",
      startDate: "2026-01-01",
      endDate: "2028-12-31",
    }
    ],
  }
  ],
},
{
  id: "kurumsal-272",
  name: "Tiryaki Dijital Akademi Global Entegrasyonu",
  source: "Kurumsal",
  status: "On Track",
  leader: "Güven Emrah Erenler",
  startDate: "2024-04-01",
  endDate: "2025-12-31",
  projects: [
  {
    id: "prj-273",
    name: "Tiryaki Dijital Akademi",
    status: "On Track",
    leader: "Güven Emrah Erenler",
    startDate: "2024-04-01",
    endDate: "2025-12-31",
    tasks: [
    {
      id: "tsk-274",
      name: "1-TDA Dijital Entegrasyonu",
      progress: 0,
      status: "Achieved",
      startDate: "2024-04-01",
      endDate: "2024-06-30",
    },
    {
      id: "tsk-275",
      name: "2-Tiryaki IT ile bir araya gelip Kanada, Irak ve Gana altyapıların araştırılması",
      progress: 0,
      status: "Achieved",
      startDate: "2024-04-01",
      endDate: "2024-06-30",
    },
    {
      id: "tsk-276",
      name: "3-Tiryaki Global lokasyonlardaki ilgili yöneticilerle görüşülmesi",
      progress: 0,
      status: "Achieved",
      startDate: "2024-10-01",
      endDate: "2024-11-29",
    },
    {
      id: "tsk-277",
      name: "4-Tiryaki Global lokasyonlarda ilgili hukuk ekipleri ile görüşmelerin yapılması",
      progress: 0,
      status: "On Track",
      startDate: "2025-08-04",
      endDate: "2025-10-31",
    },
    {
      id: "tsk-278",
      name: "5-Enocta firması ile ilgili lokasyonlardaki IT ekiplerinin bir araya getirilmesi",
      progress: 0,
      status: "On Track",
      startDate: "2025-10-06",
      endDate: "2025-10-17",
    },
    {
      id: "tsk-279",
      name: "6-Entegrasyon sürecinin yapılması",
      progress: 0,
      status: "On Track",
      startDate: "2025-10-06",
      endDate: "2025-10-31",
    }
    ],
  }
  ],
},
{
  id: "kurumsal-280",
  name: "Tiryaki LTIP Programı",
  source: "Kurumsal",
  status: "Achieved",
  leader: "Tarkan Ferhat Yılmaz",
  startDate: "2024-04-01",
  endDate: "2025-11-20",
  projects: [
  {
    id: "prj-281",
    name: "Tiryaki LTIP programının global düzeyde hayata geçirilmesi",
    status: "Achieved",
    leader: "Tarkan Ferhat Yılmaz",
    startDate: "2024-04-01",
    endDate: "2025-11-20",
    tasks: [
    {
      id: "tsk-282",
      name: "1-Tiryaki LTIP prosedür/genel kural ve koşullar dokümanların tamamlanması",
      progress: 0,
      status: "Achieved",
      startDate: "2024-04-01",
      endDate: "2024-06-30",
    },
    {
      id: "tsk-283",
      name: "2-Finans'tan 2024 finansalların alınması, stratejik finansal hedeflerin teyiti",
      progress: 0,
      status: "Achieved",
      startDate: "2024-07-16",
      endDate: "2024-08-15",
    },
    {
      id: "tsk-284",
      name: "3-2023-24 Planları-Bireysel Dağıtımların Finalize Edilerek Yönetim Onayı",
      progress: 0,
      status: "Achieved",
      startDate: "2024-08-15",
      endDate: "2024-08-25",
    },
    {
      id: "tsk-285",
      name: "4-LTIP Bireysel Mektuplarının Hazırlanması ve Paylaşımı",
      progress: 0,
      status: "Achieved",
      startDate: "2024-08-25",
      endDate: "2025-11-30",
    }
    ],
  }
  ],
},
{
  id: "kurumsal-286",
  name: "Tiryaki Yapay Zeka Projesi (TYRO)",
  source: "Kurumsal",
  status: "On Track",
  leader: "Kerime İkizler",
  startDate: "2025-10-01",
  endDate: "2026-03-31",
  projects: [
  {
    id: "prj-287",
    name: "Tiryaki Yapay Zeka Projesi (TYRO HR & TRADER Agent)",
    status: "On Track",
    leader: "Kerime İkizler",
    startDate: "2025-10-01",
    endDate: "2026-03-31",
    tasks: [
    {
      id: "tsk-288",
      name: "1-Tyro HR Agent",
      progress: 0,
      status: "On Track",
      startDate: "2025-10-01",
      endDate: "2026-03-01",
    },
    {
      id: "tsk-289",
      name: "2-Tyro Trader Agent",
      progress: 0,
      status: "On Track",
      startDate: "2025-11-03",
      endDate: "2026-03-31",
    },
    {
      id: "tsk-290",
      name: "3-Tyro EHS Modülü",
      progress: 0,
      status: "On Track",
      startDate: "2025-12-01",
      endDate: "2026-03-31",
    }
    ],
  }
  ],
},
{
  id: "kurumsal-291",
  name: "Ukrayna Kaynaklı Organik Ürün Tedarik Zincirinin Kurulması",
  source: "Kurumsal",
  status: "On Track",
  leader: "Raif Karacı",
  startDate: "2024-10-01",
  endDate: "2025-12-31",
  projects: [
  {
    id: "prj-292",
    name: "Ukrayna orijinli organik ürünlerin üretilmesi ve tedarik edilmesi",
    status: "On Track",
    leader: "Raif Karacı",
    startDate: "2024-10-01",
    endDate: "2025-12-31",
    tasks: [
    {
      id: "tsk-293",
      name: "1-Weekly meeting with org. ukr supplier",
      progress: 0,
      status: "On Track",
      startDate: "2024-10-01",
      endDate: "2025-12-31",
    },
    {
      id: "tsk-294",
      name: "2-Increasing our Ukrainian non-gmo soybean purchase",
      progress: 0,
      status: "On Track",
      startDate: "2024-10-01",
      endDate: "2025-12-31",
    }
    ],
  }
  ],
},
{
  id: "kurumsal-295",
  name: "Uluslararası Çalışma Modelleri",
  source: "Kurumsal",
  status: "On Track",
  leader: "Tarkan Ferhat Yılmaz",
  startDate: "2024-04-01",
  endDate: "2026-03-31",
  projects: [
  {
    id: "prj-296",
    name: "Uluslararası Çalışma Modelleri, Prosedür ve Sözleşmeleri",
    status: "On Track",
    leader: "Tarkan Ferhat Yılmaz",
    startDate: "2024-04-01",
    endDate: "2026-03-31",
    tasks: [
    {
      id: "tsk-297",
      name: "1-Proje ekibi ve planlamasının yapılması, kapsam ve hedefin net tanımlaması",
      progress: 0,
      status: "Achieved",
      startDate: "2024-06-10",
      endDate: "2024-06-30",
    },
    {
      id: "tsk-298",
      name: "2-Tiryaki mevcut durum analiz ve soru seti",
      progress: 0,
      status: "Achieved",
      startDate: "2024-06-25",
      endDate: "2024-07-20",
    },
    {
      id: "tsk-299",
      name: "3-Çalışma modellerinin tasarlanması ve kaynak/bütçe/risk analizleri",
      progress: 0,
      status: "On Track",
      startDate: "2024-07-21",
      endDate: "2026-04-30",
    },
    {
      id: "tsk-300",
      name: "4-Dokümantasyon ve süreçlerin finalize edilmesi",
      progress: 0,
      status: "Not Started",
      startDate: "2026-03-31",
      endDate: "2026-06-30",
    },
    {
      id: "tsk-301",
      name: "5-Yönetim sunumu ve onay aşaması",
      progress: 0,
      status: "Not Started",
      startDate: "2025-05-01",
      endDate: "2026-05-31",
    }
    ],
  }
  ],
},
{
  id: "kurumsal-302",
  name: "Grup Web Sitelerinin Yenilenmesi ve Oluşturulması",
  source: "Kurumsal",
  status: "On Track",
  leader: "Arzu Örsel",
  startDate: "2025-04-16",
  endDate: "2026-05-15",
  projects: [
  {
    id: "prj-303",
    name: "Faz 1: Tiryaki Agro web sitesinin güncellenmesi, Tiryaki Yem, Tiryaki Lidaş (19 adet site)",
    status: "On Track",
    leader: "Arzu Örsel",
    startDate: "2025-04-16",
    endDate: "2025-10-31",
    tasks: [
    {
      id: "tsk-304",
      name: "1-Capex bütçe onayının alınması",
      progress: 0,
      status: "On Track",
      startDate: "2025-04-16",
      endDate: "2025-04-30",
    },
    {
      id: "tsk-305",
      name: "2-Tedarikçi belirlenmesi ve satınalma sürecinin tamamlanması",
      progress: 0,
      status: "On Track",
      startDate: "2025-04-30",
      endDate: "2025-06-30",
    },
    {
      id: "tsk-306",
      name: "3-Tiryaki Yem, Lidaş sitelerinin tasarım ve kodlama",
      progress: 0,
      status: "Not Started",
      startDate: "2025-07-01",
      endDate: "2025-10-10",
    },
    {
      id: "tsk-307",
      name: "4-Tiryaki Anadolu web sitesinin yeni hostinge taşınması ve yayına alınması",
      progress: 0,
      status: "Not Started",
      startDate: "2025-04-16",
      endDate: "2025-10-10",
    },
    {
      id: "tsk-308",
      name: "5-Tiryaki Agro Holding sitesinin tasarlanması ve kodlanması",
      progress: 0,
      status: "Not Started",
      startDate: "2025-08-18",
      endDate: "2026-03-27",
    }
    ],
  },
  {
    id: "prj-309",
    name: "Faz 2: Tiryaki Irak, Afrika, Denizcilik ve diğer sitelerinin oluşturulması",
    status: "On Track",
    leader: "Arzu Örsel",
    startDate: "2025-09-10",
    endDate: "2026-04-24",
    tasks: [
    {
      id: "tsk-310",
      name: "1-Irak, Batı Afrika, Denizcilik, Venezüella, TiryakiNuts sitelerinin tasarımı",
      progress: 0,
      status: "On Track",
      startDate: "2025-11-20",
      endDate: "2026-04-30",
    },
    {
      id: "tsk-311",
      name: "2-Faz 2 sitelerinin kodlanmasının tamamlanması",
      progress: 0,
      status: "On Track",
      startDate: "2025-11-14",
      endDate: "2026-05-15",
    }
    ],
  },
  {
    id: "prj-312",
    name: "Faz 3: Giresunport sitesinin taşınması, Yıldız sitesinin Tiryaki Tohum ve Tiryaki'ye dönüştürülmesi",
    status: "On Track",
    leader: "Arzu Örsel",
    startDate: "2026-01-05",
    endDate: "2026-05-15",
    tasks: [
    {
      id: "tsk-313",
      name: "1-Giresunport sitesinin taşınması",
      progress: 0,
      status: "On Track",
      startDate: "2026-02-20",
      endDate: "2026-04-17",
    },
    {
      id: "tsk-314",
      name: "2-Yıldız sitesinin dönüştürülmesi",
      progress: 0,
      status: "On Track",
      startDate: "2025-12-26",
      endDate: "2026-03-20",
    }
    ],
  }
  ],
},
{
  id: "kurumsal-315",
  name: "Yetkilendirilmiş Yükümlü Statüsü (AEO) Sertifikasyonu",
  source: "Kurumsal",
  status: "On Track",
  leader: "Tamer Latifoğlu",
  startDate: "2024-07-01",
  endDate: "2025-11-30",
  projects: [
  {
    id: "prj-316",
    name: "Yetkilendirilmiş Yükümlü Sistemi Kurulumu Projesi",
    status: "On Track",
    leader: "Tamer Latifoğlu",
    startDate: "2024-07-01",
    endDate: "2025-11-30",
    tasks: [
    {
      id: "tsk-317",
      name: "1-Başvuru Ön Hazırlık",
      progress: 0,
      status: "Achieved",
      startDate: "2024-08-01",
      endDate: "2025-02-18",
    },
    {
      id: "tsk-318",
      name: "2-Bölge Müdürlüğüne Başvuru",
      progress: 0,
      status: "Achieved",
      startDate: "2025-02-18",
      endDate: "2025-02-18",
    },
    {
      id: "tsk-319",
      name: "3-Bölge Müdürlüğünün Başvuruyu Değerlendirmesi ve GM'ye sunması",
      progress: 0,
      status: "Achieved",
      startDate: "",
      endDate: "",
    },
    {
      id: "tsk-320",
      name: "4-Teftiş Kurulu Başkanlığından Müfettiş Atanması",
      progress: 0,
      status: "Achieved",
      startDate: "",
      endDate: "",
    },
    {
      id: "tsk-321",
      name: "5-Müfettiş Yerinde İnceleme ve Değerlendirme Raporunu GM'ye Sunması",
      progress: 0,
      status: "At Risk",
      startDate: "2025-10-01",
      endDate: "2025-12-31",
    },
    {
      id: "tsk-322",
      name: "6-Genel Müdürlük Başvuru Değerlendirme (Onay-Red Süreci)",
      progress: 0,
      status: "At Risk",
      startDate: "2025-12-01",
      endDate: "2025-12-31",
    }
    ],
  }
  ],
}
];

export const internationalHedefler: CascadeHedef[] = [
{
  id: "international-323",
  name: "Karbon Ticareti Programının Hayata Geçirilmesi",
  source: "International",
  status: "On Track",
  leader: "Kemal Yıldız",
  startDate: "2022-10-15",
  endDate: "2027-08-31",
  projects: [
  {
    id: "prj-324",
    name: "Karbon Ticareti Programının Hayata Geçirilmesi",
    status: "On Track",
    leader: "Kemal Yıldız",
    startDate: "2022-10-15",
    endDate: "2027-04-01",
    tasks: [
    {
      id: "tsk-325",
      name: "1-Pilot proje hazırlığı için Muş ve Giresun lands (feasibility...)",
      progress: 100,
      status: "Achieved",
      startDate: "2022-10-15",
      endDate: "2024-09-30",
    },
    {
      id: "tsk-326",
      name: "2-Selection of consultancy firms",
      progress: 100,
      status: "Achieved",
      startDate: "2022-10-15",
      endDate: "2024-09-30",
    },
    {
      id: "tsk-327",
      name: "3-Carbon certification process for Tiryaki farming Lands",
      progress: 50,
      status: "At Risk",
      startDate: "2024-01-01",
      endDate: "2026-04-01",
    },
    {
      id: "tsk-328",
      name: "4-Rolling out the implementation to entire Tiryaki Farming La...",
      progress: 0,
      status: "On Track",
      startDate: "2025-01-01",
      endDate: "2027-12-31",
    },
    {
      id: "tsk-329",
      name: "5-Rolling out the implementation to 3rd Party Farming Lands",
      progress: 0,
      status: "On Track",
      startDate: "2025-01-01",
      endDate: "2027-12-31",
    },
    {
      id: "tsk-330",
      name: "6-Carbon certification process for 3rd Party Farming Lands",
      progress: 0,
      status: "Not Started",
      startDate: "2025-11-01",
      endDate: "2027-08-31",
    },
    {
      id: "tsk-331",
      name: "7-Starting of Carbon Trade",
      progress: 0,
      status: "Not Started",
      startDate: "2026-01-01",
      endDate: "2026-08-31",
    }
    ],
  }
  ],
},
{
  id: "international-332",
  name: "Cibuti Liman Yatırımının Değerlendirilmesi",
  source: "International",
  status: "On Track",
  leader: "Nevzat Çakmak",
  startDate: "2014-04-01",
  endDate: "2027-12-31",
  projects: [
  {
    id: "prj-333",
    name: "Djibouti Port Proposal",
    status: "On Track",
    leader: "Nevzat Çakmak",
    startDate: "2014-04-01",
    endDate: "2027-12-31",
    tasks: [
    {
      id: "tsk-334",
      name: "1-Preparation for Preliminary Meeting with IFC Management",
      progress: 100,
      status: "Achieved",
      startDate: "2024-04-01",
      endDate: "2024-12-31",
    },
    {
      id: "tsk-335",
      name: "2-Preparation for Final Agreement Terms Document",
      progress: 100,
      status: "Achieved",
      startDate: "2024-04-19",
      endDate: "2024-10-16",
    },
    {
      id: "tsk-336",
      name: "3-Initiating the Process of Signing a Collaboration Agreement",
      progress: 100,
      status: "Achieved",
      startDate: "2025-05-01",
      endDate: "2025-10-22",
    },
    {
      id: "tsk-337",
      name: "4-MOU Process with the Port Authority",
      progress: 100,
      status: "Achieved",
      startDate: "2025-05-01",
      endDate: "2026-03-31",
    },
    {
      id: "tsk-338",
      name: "5-Land selection",
      progress: 100,
      status: "Achieved",
      startDate: "2025-05-01",
      endDate: "2025-11-30",
    },
    {
      id: "tsk-339",
      name: "6-Technical design (detailed version)",
      progress: 0,
      status: "Not Started",
      startDate: "2026-03-01",
      endDate: "2026-03-31",
    },
    {
      id: "tsk-340",
      name: "7-Operational Feasibility (detailed version)",
      progress: 0,
      status: "Not Started",
      startDate: "2026-03-01",
      endDate: "2026-03-31",
    },
    {
      id: "tsk-341",
      name: "8-Financial Feasibility (detailed version)",
      progress: 0,
      status: "Not Started",
      startDate: "2026-03-01",
      endDate: "2026-03-31",
    },
    {
      id: "tsk-342",
      name: "9-Final approvals of Management",
      progress: 0,
      status: "Not Started",
      startDate: "2026-03-01",
      endDate: "2026-03-31",
    },
    {
      id: "tsk-343",
      name: "10-Investment Processes (Supply, construction, agreements...)",
      progress: 0,
      status: "Not Started",
      startDate: "2026-11-01",
      endDate: "2027-12-31",
    }
    ],
  }
  ],
},
{
  id: "international-344",
  name: "Büyük El Fav Liman Projesi Katılımı",
  source: "International",
  status: "On Track",
  leader: "Fatih Tiryakioğlu",
  startDate: "2023-07-01",
  endDate: "2025-12-31",
  projects: [
  {
    id: "prj-345",
    name: "Büyük El Fav Liman Projesi Katılımı",
    status: "On Track",
    leader: "Fatih Tiryakioğlu",
    startDate: "2023-07-01",
    endDate: "2025-12-31",
    tasks: [
    {
      id: "tsk-346",
      name: "1-Feasibility Study",
      progress: 100,
      status: "Achieved",
      startDate: "2023-07-01",
      endDate: "2023-10-31",
    },
    {
      id: "tsk-347",
      name: "2-Financial Feasibility Study",
      progress: 100,
      status: "Achieved",
      startDate: "2023-07-01",
      endDate: "2024-01-01",
    },
    {
      id: "tsk-348",
      name: "3-Letter of Intent submission to the port",
      progress: 100,
      status: "Achieved",
      startDate: "2025-01-01",
      endDate: "2025-02-15",
    },
    {
      id: "tsk-349",
      name: "4-Negotiation with the port authority",
      progress: 100,
      status: "Achieved",
      startDate: "2025-01-01",
      endDate: "2025-06-30",
    },
    {
      id: "tsk-350",
      name: "5-Signing with the port authority",
      progress: 0,
      status: "On Track",
      startDate: "2025-07-01",
      endDate: "2026-10-31",
    },
    {
      id: "tsk-351",
      name: "6-Construction Period",
      progress: 0,
      status: "Not Started",
      startDate: "2026-03-01",
      endDate: "2027-12-31",
    }
    ],
  }
  ],
},
{
  id: "international-352",
  name: "Venezuela Şeker Rafinerisi Yatırımı",
  source: "International",
  status: "At Risk",
  leader: "Nevzat Çakmak",
  startDate: "2024-08-19",
  endDate: "2027-08-31",
  projects: [
  {
    id: "prj-353",
    name: "Venezuela Şeker Rafinerisi Yatırımı",
    status: "At Risk",
    leader: "Nevzat Çakmak",
    startDate: "2024-08-19",
    endDate: "2027-08-31",
    tasks: [
    {
      id: "tsk-354",
      name: "1-Feasibility and Market Analysis",
      progress: 100,
      status: "Achieved",
      startDate: "2024-08-19",
      endDate: "2026-02-29",
    },
    {
      id: "tsk-355",
      name: "2-Regulatory and Stakeholder Engagement",
      progress: 0,
      status: "At Risk",
      startDate: "2025-01-01",
      endDate: "2026-03-31",
    },
    {
      id: "tsk-356",
      name: "3-Technology Selection and Plant Design",
      progress: 0,
      status: "Not Started",
      startDate: "2025-01-01",
      endDate: "2026-03-31",
    },
    {
      id: "tsk-357",
      name: "4-Financing and Partnerships",
      progress: 0,
      status: "Not Started",
      startDate: "2025-06-01",
      endDate: "2026-06-30",
    },
    {
      id: "tsk-358",
      name: "5-Construction and Commissioning",
      progress: 0,
      status: "Not Started",
      startDate: "2026-04-01",
      endDate: "2027-08-31",
    },
    {
      id: "tsk-359",
      name: "6-Commercial Operations and Regional Integration",
      progress: 0,
      status: "Not Started",
      startDate: "2027-07-01",
      endDate: "2027-08-31",
    }
    ],
  }
  ],
},
{
  id: "international-360",
  name: "Irak Tarım Holding Yapılanmasının Kurulması",
  source: "International",
  status: "On Track",
  leader: "Bahadır Açık",
  startDate: "2026-01-01",
  endDate: "2027-12-31",
  projects: [
  {
    id: "prj-361",
    name: "Irak Tarım Holding Yapılanmasının Kurulması",
    status: "On Track",
    leader: "Bahadır Açık",
    startDate: "2026-01-01",
    endDate: "2027-12-31",
    tasks: [
    {
      id: "tsk-362",
      name: "1-Conceptual design, Approval of the GMs and shareholding",
      progress: 100,
      status: "Achieved",
      startDate: "2026-01-01",
      endDate: "2027-12-31",
    },
    {
      id: "tsk-363",
      name: "2-Establishing the AgroHolding",
      progress: 0,
      status: "On Track",
      startDate: "2025-10-01",
      endDate: "2026-06-14",
    },
    {
      id: "tsk-364",
      name: "3-Presenting the Project to the government",
      progress: 0,
      status: "Not Started",
      startDate: "2026-06-14",
      endDate: "2026-03-30",
    },
    {
      id: "tsk-365",
      name: "4-Subsidizing the Project to the international and local banks",
      progress: 0,
      status: "Not Started",
      startDate: "2026-03-01",
      endDate: "2026-06-30",
    },
    {
      id: "tsk-366",
      name: "5-Execution of the contract with the government for privileges",
      progress: 0,
      status: "Not Started",
      startDate: "2026-03-01",
      endDate: "2026-06-30",
    },
    {
      id: "tsk-367",
      name: "6-Subsidizing the Project to the international and local banks",
      progress: 0,
      status: "Not Started",
      startDate: "2026-03-01",
      endDate: "2026-06-30",
    },
    {
      id: "tsk-368",
      name: "7-Starting the Project engineering phase",
      progress: 0,
      status: "Not Started",
      startDate: "2026-03-01",
      endDate: "2026-09-01",
    },
    {
      id: "tsk-369",
      name: "8-Constructing investment in accordance with the approvals...",
      progress: 0,
      status: "Not Started",
      startDate: "2026-09-01",
      endDate: "2027-12-31",
    }
    ],
  }
  ],
},
{
  id: "international-370",
  name: "Irak Organizasyonel Uyum ve Eğitim Programı",
  source: "International",
  status: "At Risk",
  leader: "Güven Emrah Erenler",
  startDate: "2024-05-31",
  endDate: "2026-06-30",
  projects: [
  {
    id: "prj-371",
    name: "Irak Organizasyonel Uyum ve Eğitim Programı",
    status: "At Risk",
    leader: "Güven Emrah Erenler",
    startDate: "2024-05-31",
    endDate: "2026-06-30",
    tasks: [
    {
      id: "tsk-372",
      name: "1-Completion of technical and mandatory OHS training",
      progress: 100,
      status: "Achieved",
      startDate: "2024-05-31",
      endDate: "2024-06-30",
    },
    {
      id: "tsk-373",
      name: "2-Leadership and Personal Development Trainings",
      progress: 100,
      status: "Achieved",
      startDate: "2024-05-31",
      endDate: "2024-06-30",
    },
    {
      id: "tsk-374",
      name: "3-Monthly routines reporting structure to be set",
      progress: 0,
      status: "On Track",
      startDate: "2026-01-01",
      endDate: "2026-05-20",
    },
    {
      id: "tsk-375",
      name: "4-Hire Future Leader",
      progress: 0,
      status: "Not Started",
      startDate: "2025-11-19",
      endDate: "2026-06-30",
    }
    ],
  }
  ],
},
{
  id: "international-376",
  name: "Afrika Ülke Yapılanmalarının Gözden Geçirilmesi",
  source: "International",
  status: "On Track",
  leader: "Güven Emrah Erenler",
  startDate: "2026-03-01",
  endDate: "2028-06-30",
  projects: [
  {
    id: "prj-377",
    name: "Afrika Ülke Yapılanmalarının Gözden Geçirilmesi and organisational apl.",
    status: "On Track",
    leader: "Güven Emrah Erenler",
    startDate: "2026-03-01",
    endDate: "2024-09-30",
    tasks: [
    {
      id: "tsk-378",
      name: "1-Establishing the org. structure, designing org charts with a..",
      progress: 100,
      status: "Achieved",
      startDate: "2026-04-04",
      endDate: "2024-10-01",
    },
    {
      id: "tsk-379",
      name: "2-Filling the vacant positions of 4 employees",
      progress: 0,
      status: "On Track",
      startDate: "2026-11-16",
      endDate: "2026-08-31",
    },
    {
      id: "tsk-380",
      name: "3-Designing Africa remuneration and benefits strategies",
      progress: 0,
      status: "Not Started",
      startDate: "2026-05-01",
      endDate: "2026-06-30",
    },
    {
      id: "tsk-381",
      name: "4-Nigeria task",
      progress: 0,
      status: "Not Started",
      startDate: "2026-04-19",
      endDate: "2026-08-31",
    },
    {
      id: "tsk-382",
      name: "5-Guinea visit",
      progress: 0,
      status: "Not Started",
      startDate: "",
      endDate: "",
    }
    ],
  }
  ],
},
{
  id: "international-383",
  name: "Venezuela Kömür Tesisi Projesi",
  source: "International",
  status: "At Risk",
  leader: "Bahadır Açık",
  startDate: "2025-07-01",
  endDate: "2028-12-31",
  projects: [
  {
    id: "prj-384",
    name: "Venezuela Kömür Tesisi Projesi",
    status: "At Risk",
    leader: "Bahadır Açık",
    startDate: "2025-07-01",
    endDate: "2028-12-31",
    tasks: [
    {
      id: "tsk-385",
      name: "1-Site Assessment and Resource Evaluation",
      progress: 0,
      status: "On Track",
      startDate: "2025-07-01",
      endDate: "2026-05-31",
    },
    {
      id: "tsk-386",
      name: "2-Identification of Investment and Capacity Requirements",
      progress: 0,
      status: "On Track",
      startDate: "2025-01-01",
      endDate: "2025-10-31",
    },
    {
      id: "tsk-387",
      name: "3-Final Financial and Environmental Studies",
      progress: 0,
      status: "On Track",
      startDate: "2026-03-01",
      endDate: "2026-05-15",
    },
    {
      id: "tsk-388",
      name: "4-Consultation and Agreement Processes with Authorities",
      progress: 0,
      status: "Not Started",
      startDate: "2026-03-01",
      endDate: "2026-06-30",
    },
    {
      id: "tsk-389",
      name: "5-Detailed Investments and Engineering Planning",
      progress: 0,
      status: "Not Started",
      startDate: "2026-03-01",
      endDate: "2026-06-30",
    },
    {
      id: "tsk-390",
      name: "6-Procurement and Logistics Preparation",
      progress: 0,
      status: "Not Started",
      startDate: "2026-05-01",
      endDate: "2026-11-30",
    },
    {
      id: "tsk-391",
      name: "7-Equipment and Facility Installation",
      progress: 0,
      status: "Not Started",
      startDate: "2026-05-01",
      endDate: "2026-11-30",
    },
    {
      id: "tsk-392",
      name: "8-Testing, Commissioning and Start of Operations",
      progress: 0,
      status: "Not Started",
      startDate: "2026-03-01",
      endDate: "2028-12-31",
    }
    ],
  }
  ],
}
];

export const allHedefler: CascadeHedef[] = [
  ...turkiyeHedefler,
  ...kurumsalHedefler,
  ...internationalHedefler,
];
